global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert-rules.yml
  
scrape_configs:
  - job_name: "librarylite"
    static_configs:
      - targets: ["app:8000"]
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

